export default [
    {
        name: "FraDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Francesco",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "LuDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Lucas",
        description: "Programmatore sgravato, sicurezza certa, kangaskhan, qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "ArriDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Arrigo",
        description: "Designer madonnale, probabilmente l'unico che non mangia colla, qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "HenryDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Enrico",
        description: "Conosci un'artista? Se non conosci Enrico ancora non sai cosa è veramente un'artista, qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "DaviDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Davide",
        description: "Hai bisogno di arte? Di freschezza? Di sicurezza? Guarda qua qua qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "TeoDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Matteo",
        description: "La parola programmatore impersonificata. Anzi, meglio. IL DRAGONE, qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "FedeDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Federico",
        description: "orecchio assoluto, musicista e composer troppo forte. Forte come skill, non come rumore, qua qua musicale",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "LoreDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Lorenzo",
        description: "Hai bisogno di un character? Bisogno di sentire un pò di novità scorrerti dentro? Scegli Lore qua qua",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
]
