export default [
    {
        name: "FraDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Francesco",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "LuDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Lucas",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "ArriDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Arrigo",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "Duck4",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Duck 4",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "Duck5",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Duck 5",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "Duck6",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Duck 6",
        description: "questa è un'anatra",
        profileLink: "link",
    },
    {
        name: "Duck7",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Duck 7",
        description: "questa è un'anatra",
        profileLink: "link",
    },
]
