export default [
    {
        name: "FraDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Francesco",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "LuDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Lucas",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "ArriDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Arrigo",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "HenryDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Enrico",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "DaviDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Davide",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "TeoDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Matteo",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "FedeDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Federico",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
    {
        name: "LoreDuck",
        type: 'texture',
        path: 'textures/pond/Duck.png',
        title: "Lorenzo",
        description: "questa è un'anatra",
        profileLink: "https://francesco-portfolio.vercel.app/",
    },
]
